### /posts/:postId/comments
POST http://localhost:3000/posts/456aa524-9682-4763-b102-5452223c0b94/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhMmI2OGM1Mi1mNzYwLTQyYWEtYjk5OC0zMjhhMDhjZTkwZWIiLCJyb2xlcyI6WyJ1c2VyIl0sImlhdCI6MTYyNzQ3NDA4MiwiZXhwIjoxNjI3NDc3NjgyfQ.gdx9nfEE0ihESWn_jzSiyrng21ha4cuFMegdNqSPkSk
Content-Type: application/json

{
  "description": "description-post"
}

###
GET http://localhost:3000/posts/456aa524-9682-4763-b102-5452223c0b94/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhMmI2OGM1Mi1mNzYwLTQyYWEtYjk5OC0zMjhhMDhjZTkwZWIiLCJyb2xlcyI6WyJ1c2VyIl0sImlhdCI6MTYyNzQ3NDA4MiwiZXhwIjoxNjI3NDc3NjgyfQ.gdx9nfEE0ihESWn_jzSiyrng21ha4cuFMegdNqSPkSk
